def draw_snowman(number_of_lives):
    """
    Draws snowman drawing based on failed attempts variable
    from run.py
    """
    if number_of_lives == 10:
        print("\n")
        print("*   *    *   *   *   *    *     *    *  *   *   *    *    *")
        print("  *    *    *     *    *    *    *     *      *    *    *  ")
        print("*     *   *    *    *   *    *     *    *  *    *    *    *")
        print("   *    *   ______   *     *    *    *    *   *    *    *  ")
        print("*    *   __|______|__   *   *    *    *   *     *    *    *")
        print("    *      /      \\      *    *    *   *    *     *    *   ")
        print("  *  \\|/  |  ' < ' |   \\|/     *    *   *   *    *   *    *")
        print("*   *  \\   \\______/    /    *   *   *    *    *    *   *   ")
        print("  *     \\  /       \\  /  *    *    *   *    *   *    *    *")
        print("*   *    \\/    0    \\/      *     *     *   *    *   *   * ")
        print("  *      |     0     |   *   *    *    *   *   *     *     *")
        print("   *   *  \\    0    /    *    *    *   *     *    *     *  ")
        print("*    *     \\_______/   *     *    *     *   *   *    *    *")
        print("\n")
    elif number_of_lives == 9:
        print("\n")
        print("*        *      *       *       *        *        *       *")
        print("    *         *           *          *        *        *   ")
        print("*          *          *        *          *        *       ")
        print("   *        ______        *          *        *       *    ")
        print("*        __|______|__         *         *         *       *")
        print("    *      /      \\             *          *         *     ")
        print("     \\|/  |  ' < ' |   \\|/        *           *           *")
        print("*      \\   \\______/    /    *           *           *      ")
        print("   *    \\  /       \\  /          *         *               ")
        print("*        \\/    0    \\/     *         *           *         ")
        print("         |     0     |             *         *          *   ")
        print("    *     \\    0    /        *        *           *        ")
        print("*          \\_______/    *       *         *          *    *")
        print("\n")
    elif number_of_lives == 8:
        print("\n")
        print("*        *      *       *       *          *        *     *")
        print("    *                *              *          \\|/    *   ")
        print("*          *            *              *     -- O --       ")
        print("   *        ______            *                /|\\    *   ")
        print("*        __|______|__               *                     *")
        print("    *      /      \\             *          *         *     ")
        print("     \\|/  |  ' < ' |   \\|/           *         *          *")
        print("*      \\   \\______/    /       *         *          *      ")
        print("   *    \\  /       \\  /             *         *           *")
        print("*        \\/    0    \\/        *         *         *        ")
        print("         |     0     |               *         *           *")
        print("   *      \\    0    /        *        *           *        ")
        print("*    *     \\_______/    *       *         *          *    *")
        print("\n")
    elif number_of_lives == 7:
        print("\n")
        print("*        *      *       *       *          *        *     *")
        print("    *                *              *          \\|/    *   ")
        print("*          *            *              *     -- O --       ")
        print("   *        ______            *                /|\\    *   ")
        print("*        __|______|__               *                     *")
        print("    *      /      \\             *          *         *     ")
        print("     \\|/  |  ' < ' |   \\|/           *         *          *")
        print("*      \\   \\______/    /       *         *          *      ")
        print("   *    \\  /       \\  /             *         *           *")
        print("*        \\/    0    \\/        *         *         *        ")
        print("         |     0     |               *         *           *")
        print("   *      \\    0    /        *        *           *        ")
        print("*    *     \\_______/    *       *         *          *    *")
        print("\n")
    elif number_of_lives == 6:
        print("\n")
        print("*   *     *      *       *     *     *      *        *    *")
        print("  *   *     *     *    *        *      *      \\|/      *  ")
        print("*      *       *    *   *    *     *        -- O --       *")
        print("   *    *   ______   *     *    *    *    *   /|\\      *  ")
        print("*    *   __|______|__   *   *        *   *                *")
        print("    *      /      \\      *       *  _________   *      *   ")
        print("  *  \\|/  |  ' < ' |   \\|/     *   |  HELP!  |      *     *")
        print("*      \\   \\______/    /    *      |_________|   *     *   ")
        print("  *     \\  /       \\  /        *   |        *       *     *")
        print("*   *    \\/    0    \\/      *      |     *       *       * ")
        print("  *      |     0     |   *       * |         *       *     *")
        print("   *   *  \\    0    /    *    *    |   *         *      *  ")
        print("*    *     \\_______/   *     *     |       *        *     *")
        print("\n")
    elif number_of_lives == 5:
        print("\n")
        print("Placeholder for 5 lives")
        print("\n")
    elif number_of_lives == 4:
        print("\n")
        print("Placeholder for 4 lives")
        print("\n")
    elif number_of_lives == 3:
        print("\n")
        print("Placeholder for 3 lives")
        print("\n")
    elif number_of_lives == 2:
        print("\n")
        print("Placeholder for 2 lives")
        print("\n")
    elif number_of_lives == 1:
        print("\n")
        print("Placeholder for 1 live")
        print("\n")
